config/routes.rb
Rails.application.routes.draw do

  scope '/:locale', locale: /#{I18n.available_locales.join('|')}/ do
    root to: 'application#home'
  end

  get 'getstarted/thankyou'

  get 'getstarted/basic' => redirect("https://basicplan.carrd.co/") # Recopie ca pour les deux autres plans
  get 'getstarted/basic_confirm', to: 'getstarted#basic_confirm'

  get 'getstarted/intermediate'=> redirect("https://intermediateplan.carrd.co/")
  get 'getstarted/intermediate_confirm', to: 'getstarted#intermediate_confirm'

  get 'getstarted/pro'=> redirect("https://proplan.carrd.co/")
  get 'getstarted/pro_confirm', to: 'getstarted#pro_confirm'

  get '/faq', to: 'pages#faq'
  get '/blog', to: 'pages#blog'
  get '/jobs', to: 'pages#jobs'
  get '/terms', to: 'pages#terms'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'application#home'
end

app/models/concerns/stripe_tool.rb
  def self.create_membership(email: email, stripe_token: stripe_token, plan: plan)
    Stripe::Customer.create(
      email: email,
      source: stripe_token,
      plan: plan
    )
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_locale

  def home
  end

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/getstarted_controller.rb
class GetstartedController < ApplicationController
  def basic
  end

  def basic_confirm
  end

  def intermediate
  end

  def intermediate_confirm
  end

  def pro
  end

  def pro_confirm
  end

  def thankyou
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def faq
  end

  def blog
  end

  def jobs
  end

  def terms
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/getstarted_helper.rb
module GetstartedHelper
end

app/views/application/_banner.html.erb
<div id="banner">
  <h1 class="banner-title">
    BUILD A <strong>STRONG</strong>, <strong>ACTIVE</strong> AND
    <strong>RELIABLE</strong> COMMUNITY
    <br>
    AROUND YOUR BUSINESS ON <span class="insta-word">INSTAGRAM</span>
  </h1> <!-- End .banner-title -->

  <p class="banner-desc">
    Grow your instagram community with real and organic followers.
    <br>
    <span class="hidden-xs">
       Get up to +1.500 targeted followers per month with minimal effort on your part.
    <br>
    Turn followers into loyal customers.
    <br>
    <br>
    </span>
    Exactly like <strong>A HUMAN</strong> with <span class="super-social-word">SUPER SOCIAL MEDIA POWER</span> would do.
  </p> <!-- End .banner-desc -->

  <button class="primary-button">
    <a href="#pricing"><%= t('landing.buttons.primary_button') %></a>
  </button>
</div>

app/views/application/_contact.html.erb
<div id="contact">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <div class="contact-us">
          Influencers, Personal Brand, Start-up, Digital Company &#038; more
          <br><br>
          <div class="we-can-help">We can help you...</div>
        </div>
      </div>
    </div>
  </div>
  <%= image_tag("iphone-mockup-final.png", class: "iphone-mock-up hidden-xs") %>
</div>

app/views/application/_how.html.erb
<div id="how">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <h2 class="section-title">How it works?</h2>
      </div>
    </div>

    <div class="row feature">
      <!-- Illustration mobile & desktop -->
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <%= image_tag("illu-test.png", class: "feature-illu") %>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <div class="feature-content">
          <div class="feature-content-vert">
            <h3 class="feature-title">Develop an Instagram Strategy</h3>
            <div class="features-desc"> Through an online form, our team will get a better understanding of how your business works: where your target audience is located, what they are interested in, and which other accounts they follow.</div>
          </div>
        </div>
      </div>
    </div><!-- End .row .feature -->

    <div class="row feature">
      <!-- Illustration mobile -->
      <div class="hidden-sm hidden-md hidden-lg">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
          <%= image_tag("illu-test.png", class: "feature-illu") %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <div class="feature-content">
          <div class="feature-content-vert">
            <h3 class="feature-title">Configuration of Your Campaign</h3>
            <div class="features-desc">Next we will configure the chosen targeting strategy into our software. Your account will then start interacting automatically with your target audience. These interactions are most often a combination of liking pictures and following users within a specific market.</div>
          </div>
        </div>
      </div>
      <!-- Illustration desktop -->
      <div class="hidden-xs">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
          <%= image_tag("illu-test.png", class: "feature-illu") %>
        </div>
      </div>
    </div><!-- End .row .feature -->

    <div class="row feature">
      <!-- Illustration mobile & desktop -->
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <%= image_tag("illu-test.png", class: "feature-illu") %>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <div class="feature-content">
          <div class="feature-content-vert">
            <h3 class="feature-title">Increased Brand Awareness</h3>
            <div class="features-desc">As soon as the first interactions are initiated, results are visible instantly. Your Instagram profile will grow faster by receiving more likes, comments and followers. There will be a growing stream of traffic to your website as more users discover your profile.</div>
          </div>
        </div>
      </div>
    </div><!-- End .row .feature -->

    <div class="row feature">
      <!-- Illustration mobile -->
      <div class="hidden-sm hidden-md hidden-lg">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
          <%= image_tag("illu-test.png", class: "feature-illu") %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <div class="feature-content">
          <div class="feature-content-vert">
            <h3 class="feature-title">Increased Sales Conversions</h3>
            <div class="features-desc">Once your campaign launches, the amplification machine starts. Targeted followers are leads to your business. Leads can be turn into loyal customers.</div>
          </div>
        </div>
      </div>
      <!-- Illustration desktop -->
      <div class="hidden-xs">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
          <%= image_tag("illu-test.png", class: "feature-illu") %>
        </div>
      </div>
    </div> <!-- End .row .feature -->
  </div>
</div>

app/views/application/_pricing.html.erb
<div id="pricing">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
        <div class="card-pricing">
          <div class="card-pricing-content">
            <div class="amount-followers">
              <p><strong>700 - 1000</strong> <br> <span>targeted Followers per month</span></p>
            </div>
            <ul>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-checked"></i>
                <p>Follow / Unfollow</p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-checked"></i>
                <p>Like</p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-checked"></i>
                <p>Limited support</p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-checked"></i>
                <p>Monthly report</p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-unchecked"></i>
                <p>Comments</p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-unchecked"></i>
                <p>Direct Messages</p>
              </li>
            </ul>
          </div>
          <div class="card-pricing-footer">
            <h3 class="pricing-title">STARTER</h3>
            <div class="price">59 €</div>
            <button class="primary-button pricing-button">
              <%= link_to 'Get Started', getstarted_basic_path %>
            </button>
          </div>
        </div>
        <div class="cup-coffee text-center">
          *or 1 cup of <%= image_tag("emoji-coffee.png", class: "emoji") %> a day
          <%= image_tag("emoji-smile.png", class: "emoji") %>
        </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
        <div class="card-pricing">
          <div class="card-pricing-content">
            <ul>
              <li class="pricing-spec amount-followers">
                <p><strong>1000 - 1500</strong> <br> <span>targeted Followers per month</span></p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-checked"></i>
                <p>Follow / Unfollow</p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-checked"></i>
                <p>Like</p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-checked"></i>
                <p>Limited support</p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-checked"></i>
                <p>Monthly report</p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-checked"></i>
                <p>Comments</p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-unchecked"></i>
                <p>Direct Messages</p>
              </li>
            </ul>
          </div>
          <div class="card-pricing-footer">
            <h3 class="pricing-title">STANDARD</h3>
            <div class="price">89 €</div>
            <button class="primary-button pricing-button">
              <%= link_to 'Get Started', getstarted_intermediate_path %>
            </button>
          </div>
        </div>
        <div class="cup-coffee text-center">
          *or 2 cup of <%= image_tag("emoji-coffee.png", class: "emoji") %> a day
          <%= image_tag("emoji-smile.png", class: "emoji") %>
        </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
        <div class="card-pricing">
          <div class="card-pricing-content">
            <ul>
              <ul>
              <li class="pricing-spec amount-followers">
                <p><strong>+ 1500</strong> <br> <span>targeted Followers per month</span></p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-checked"></i>
                <p>Follow / Unfollow</p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-checked"></i>
                <p>Like</p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-checked"></i>
                <p>Comments</p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-checked"></i>
                <p>Direct Messages</p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-checked"></i>
                <p>Limited support</p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-checked"></i>
                <p>Monthly report</p>
              </li>
            </ul>
            </ul>
          </div>
          <div class="card-pricing-footer">
            <h3 class="pricing-title">PLUS</h3>
            <div class="price">159 €</div>
            <button class="primary-button pricing-button">
              <%= link_to 'Get Started', getstarted_pro_path %>
            </button>
          </div>
        </div>
        <div class="cup-coffee text-center">
          *or 3 cup of <%= image_tag("emoji-coffee.png", class: "emoji") %> a day
          <%= image_tag("emoji-smile.png", class: "emoji") %>
        </div>
      </div>
    </div>
</div>

app/views/application/_why.html.erb
<div id="why">
  <div class="container text-center">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <h2 class="section-title">Why choose iggrow?</h2>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="tututu text-center">
          <strong>iggrow</strong> provides one-of-a-kind service for organically growing your Instagram following. We combine the power of automation with human-moderated targeting so that brands and consumers connect. We know just how to strategize for top performance to see return of investment with your Instagram account(s). iggrow is like having your own social media manager, and costs less than half the price!
          <br><br>
          <br> Likes and Follows are digital currency. It builds trust and trust leads to corporate credibility and reputation.<br>
          Get started Today and reach your audience with us!
        </div>
      </div>

    </div>

    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <div class="card-type content-right">
          <%= image_tag("002-group.svg", class: "icon-card-type mlrauto-mobile") %>
          <h3>Influencer</h3>
          <div class="card-type-desc">
            Are you an Instagram’s rising star or already an established
            <br>
            Influencer? We will help you build an engaged online
            <br>
            community around your profile!
          </div>
          <ul>
            <li>
              <span class="right hidden-sm hidden-md hidden-lg">•</span>
              Reach more followers in your niche
              <span class="left hidden-xs">•</span>
            </li>
            <li>
              <span class="right hidden-sm hidden-md hidden-lg">•</span>
              Improve engagement on you content
              <span class="left hidden-xs">•</span>
            </li>
            <li>
              <span class="right hidden-sm hidden-md hidden-lg">•</span>
              Get recognized in your industry
              <span class="left hidden-xs">•</span>
            </li>
            <li>
              <span class="right hidden-sm hidden-md hidden-lg">•</span>
              Build a strong personal brand
              <span class="left hidden-xs">•</span>
            </li>
            <li>
              <span class="right hidden-sm hidden-md hidden-lg">•</span>
              Monetize your popularity
              <span class="left hidden-xs">•</span>
            </li>
          </ul>
          <button class="secondary-button"> <a href="#pricing">Get Started with <strong>influencer</strong></a></button>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <div class="card-type content-left">
          <%= image_tag("001-employee.svg", class: "icon-card-type mlrauto-mobile") %>
          <h3>Business</h3>
          <div class="card-type-desc">
            Is Instagram presence just a part of your online business strategy?
            <br>
            We will help you reach your target audience and drive more sales to your business!
          </div>
          <ul >
            <li><span class="right">•</span>Grow your brand’s awareness</li>
            <li><span class="right">•</span>Drive more sales to your business</li>
            <li><span class="right">•</span>Connect with Top Influencers from your industry</li>
            <li><span class="right">•</span>Improve customer engagement</li>
            <li><span class="right">•</span>Expand to new markets easily</li>
          </ul>
          <button class="secondary-button"> <a href="#pricing">Get Started with <strong>business</strong></a></button>
        </div>
      </div>
    </div>
  </div>
</div>

<hr>

app/views/application/home.html.erb
<!-- Navbar -->
<%= render 'shared/navbar' %>

<!-- Banner -->
<%= render "application/banner" %>

<!-- Why -->
<%= render "application/why" %>

<!-- How -->
<%= render "application/how" %>

<!-- Pricing -->
<%= render "application/pricing" %>

<!-- Contact -->
<%= render "application/contact" %>

<!-- Footer -->
<%= render 'shared/footer' %>

app/views/getstarted/basic.html.erb
<!-- Basic Form -->

<div class="text-center" id="banner">
  <div class="typeform-widget" data-url="https://brucewayne465.typeform.com/to/ctF3YE" data-transparency="100" data-hide-headers=true data-hide-footer=true style="width: 100%; height: 500px;" > </div> <script> (function() { var qs,js,q,s,d=document, gi=d.getElementById, ce=d.createElement, gt=d.getElementsByTagName, id="typef_orm", b="https://embed.typeform.com/"; if(!gi.call(d,id)) { js=ce.call(d,"script"); js.id=id; js.src=b+"embed.js"; q=gt.call(d,"script")[0]; q.parentNode.insertBefore(js,q) } })() </script>

  <button class="primary-button confirm-button">
    <%= link_to 'Confirm your plan', getstarted_basic_confirm_path %>
  </button>
</div>

app/views/getstarted/basic_confirm.html.erb
<button class="btn btn-primary btn-large" id="stripe-demo">Subscribe</button>

<script src="https://checkout.stripe.com/checkout.js"></script>
<script>
var handler = StripeCheckout.configure({
  key: "pk_test_1MCYLYHQDa4DwnBoKd5CqoaP",
  image: "https://stripe.com/img/documentation/checkout/marketplace.png",
  name: "Demo SaaS Site",
  description: "Pro Subscription ($29 per month)",
  panelLabel: "Subscribe",
  allowRememberMe: false
});

document.getElementById('stripe-demo').addEventListener('click', function(e) {
  handler.open();
  e.preventDefault();
});
</script>

app/views/getstarted/intermediate.html.erb
<!-- Intermediate Form -->

<div class="text-center" id="banner">
  <div class="typeform-widget" data-url="https://brucewayne465.typeform.com/to/m5FeUy" data-transparency="100" data-hide-headers=true data-hide-footer=true style="width: 100%; height: 500px;" > </div> <script> (function() { var qs,js,q,s,d=document, gi=d.getElementById, ce=d.createElement, gt=d.getElementsByTagName, id="typef_orm", b="https://embed.typeform.com/"; if(!gi.call(d,id)) { js=ce.call(d,"script"); js.id=id; js.src=b+"embed.js"; q=gt.call(d,"script")[0]; q.parentNode.insertBefore(js,q) } })() </script>

  <button class="primary-button confirm-button">
    <%= link_to 'Confirm your plan', getstarted_intermediate_confirm_path %>
  </button>
</div>

app/views/getstarted/intermediate_confirm.html.erb
intermediate_confirm.html.erb

app/views/getstarted/pro.html.erb
<!-- Pro Form -->

<div class="text-center" id="banner">
  <div class="typeform-widget" data-url="https://brucewayne465.typeform.com/to/basYMj" data-transparency="100" data-hide-headers=true data-hide-footer=true style="width: 100%; height: 500px;" > </div> <script> (function() { var qs,js,q,s,d=document, gi=d.getElementById, ce=d.createElement, gt=d.getElementsByTagName, id="typef_orm", b="https://embed.typeform.com/"; if(!gi.call(d,id)) { js=ce.call(d,"script"); js.id=id; js.src=b+"embed.js"; q=gt.call(d,"script")[0]; q.parentNode.insertBefore(js,q) } })() </script>

  <button class="primary-button confirm-button">
    <%= link_to 'Confirm your plan', getstarted_pro_confirm_path %>
  </button>
</div>

app/views/getstarted/pro_confirm.html.erb
pro_confirm.html.erb

app/views/getstarted/thankyou.html.erb
<div class="text-center" id="thankyou" >
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h1>Thank You</h1>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Growth for influencers - IGGROW</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag 'favicon.png' %>
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
    <!-- Stylesheet -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://js.stripe.com/v3/', 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/blog.html.erb
<!-- Navbar -->
<%= render 'shared/navbar_pages' %>

<div id="blog">
  <div class="banner-pages">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <h1>Instagram Marketing Stratedy, Tips, Tools and Guides</h1>
        </div>
      </div>
    </div>
  </div> <!-- End .banner-pages -->

  <div class="pages-content">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <h2>Under Construction</h2>
        </div>
      </div>
    </div>
  </div>


</div>

<!-- Footer -->
<%= render 'shared/footer_pages' %>

app/views/pages/faq.html.erb
<%= render 'shared/navbar_pages' %>

<div class="banner-pages">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <h1>Frequently asked questions</h1>
      </div>
    </div>
  </div>
</div>

<div id="faq">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
        <div class="faq-card">
          <h2 class="question">How many followers should i expect to gain everyday?</h2>
          <div class="answer">There are many factors to this. From size and age of account to content and engagement. However, an average would be from 20-100 followers a day.</div>
        </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
        <div class="faq-card">
          <h2 class="question">What type of activity will IGGROW generate for me?</h2>
          <div class="answer">Likes, Following, and Unfollowing. However, if you wish to remove one of these you can do so by emailing us.</div>
        </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
        <div class="faq-card">
          <h2 class="question">How is the activity targeted?</h2>
          <div class="answer">IGGROW encourages you to research the hashtags you wish to target and usernames of accounts you want to target. Your quality of followers will highly rely on the types of hashtags and usernames you provide us with.</div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
        <h2 class="question">Will IGGROW unfollow people i am currently following?</h2>
        <div class="answer">No, we create what we call The Safelist. The Safelist is a list of the people you were following at the moment of signing up. That way we make sure to never unfollow those people.</div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
        <h2 class="question">What if i follow someone while the service is running? Will you unfollow them?</h2>
        <div class="answer">In that case can email us mentionning the username and we will automatically add that username to The Safelist.</div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
        <h2 class="question">How much will i pay for IGGROW?</h2>
        <div class="answer">Our service starts at $59 a month. However, you can cancel at any time by emailing us.</div>
      </div>
    </div>

    <!-- Row -->
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
        <h2 class="question">Do I have dashboard to interact with?</h2>
        <div class="answer">No, that’s what makes us that much better than our competitors! Instead of having to constantly update your account, you just provide us with the hashtags and usernames and we take care of the rest.
        Making sure your account runs flawlessly.</div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
        <h2 class="question">How many hashtags and usernames do I need to provide to IGGROW?</h2>
        <div class="answer">About up to 15 hashtags and 15 usernames should be enough for the month.</div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
        <h2 class="question">Are these real followers?</h2>
        <div class="answer">Yes all new followers are 100% real and targeted. You may find some places online that sell followers, these are mostly farmed networks or fake accounts. That is not what we offer.</div>
      </div>
    </div>

    <!-- Row -->
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
        <h2 class="question">How do you do it?</h2>
        <div class="answer">I'm glad you asked, it's magic. Actually it's pretty simple. Each day we'll perform many tasks in order to grow your account, following, unfollowing, liking, etc to organically grow your audience.</div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
        <h2 class="question">Do you post content to my account?</h2>
        <div class="answer">You remain in control of all the content you post. We do not post any content for you. This allows you to solely focus on posting the best material possible, while we focus on bringing you the right audience to view your posts. It is important that you continue posting content regularly to your account, as potential new followers only tend to follow active accounts.</div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
        <h2 class="question">Why does the number of new followers each month vary?</h2>
        <div class="answer">There are several factors. In general, it is related to the size of the account from the start and target niche. Once we get good momentum with growing your followers, the faster we can run with results every month.</div>
      </div>
    </div>

    <!-- Row -->
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
        <h2 class="question">Why should I post content to my account regularly?</h2>
        <div class="answer">It is important to continue posting content to your account on a regular basis. Since these are real people, they're much more likely to follow and remain following an active account.</div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
        <h2 class="question">Can I keep posting? Can I still follow and unfollow accounts?</h2>
        <div class="answer">Yes! You can resume doing your normal activity. We will be working in the background, but your account will still be 100% in your possession.</div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
        <h2 class="question">How quickly will my Growth Engine be underway?</h2>
        <div class="answer">New campaigns are generally underway within 48 hours, and a marketing expert at Iggrow will be in touch as soon as it kicks off to let you know.</div>
      </div>
    </div>

    <!-- Row -->
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
        <h2 class="question">Do I have to verify my account?</h2>
        <div class="answer">You will likely need to verify your account. This happens from multiple computer logins. Your social media platform is just confirming with you to secure your account. Don’t worry, your account is 100% safe.</div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
        <h2 class="question">How do I get started?</h2>
        <div class="answer">It’s pretty simple, after you purchase you will receive a brief questionnaire. Here you will provide all the info your geek will need and they'll be in touch to let you know they're getting started. Done and done.</div>
      </div>
    </div>
  </div>
</div>

<%= render 'shared/footer_pages' %>